export const quotes = [
  { text: "Jika kamu tidak bisa membuat orang lain bahagia, minimal jangan buat mereka bersedih.", author: "Imam Al-Ghazali" },
  { text: "Lidah yang jujur adalah tanda hati yang bersih.", author: "Imam Ali bin Abi Thalib" },
  { text: "Orang yang paling dicintai Allah adalah yang paling bermanfaat bagi manusia.", author: "HR. Thabrani" },
  { text: "Bersabarlah, karena sesungguhnya Allah bersama orang-orang yang sabar.", author: "Al-Quran 8:46" },
  { text: "Jangan pernah meremehkan kebaikan sekecil apapun.", author: "Imam An-Nawawi" },
  { text: "Ilmu itu lebih baik daripada harta. Ilmu menjagamu, sedangkan kamu menjaga harta.", author: "Imam Ali bin Abi Thalib" },
  { text: "Jadilah seperti pohon yang berbuah, semakin berbuah semakin merunduk.", author: "Pepatah Arab" },
  { text: "Sesungguhnya amal itu tergantung niatnya.", author: "HR. Bukhari & Muslim" },
  { text: "Barangsiapa yang hari ini lebih baik dari kemarin, maka dia beruntung.", author: "Imam Al-Ghazali" },
  { text: "Dunia adalah jembatan, maka seberangilah dan jangan mendirikan bangunan di atasnya.", author: "Nabi Isa (dalam hadis)" },
  { text: "Tanda orang berakal adalah ia yang mampu menahan diri dari berbicara ketika marah.", author: "Imam Ali bin Abi Thalib" },
  { text: "Ilmu tanpa amal seperti pohon tanpa buah.", author: "Imam Al-Ghazali" },
  { text: "Bersyukur atas nikmat yang ada lebih baik daripada mengeluhkan yang tidak ada.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Jangan bersedih atas apa yang luput darimu, karena itulah yang Allah pilihkan untukmu.", author: "Ibnu Taimiyyah" },
  { text: "Kekayaan sejati bukan pada banyaknya harta, melainkan pada kekayaan jiwa.", author: "HR. Bukhari" },
  { text: "Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lainnya.", author: "HR. Ahmad" },
  { text: "Sabar bukan berarti pasif, tapi tetap bergerak meski dalam tekanan.", author: "Imam Syafi'i" },
  { text: "Jika engkau tidak mampu berbuat baik kepada semua orang, minimal jangan menyakiti siapapun.", author: "Imam Al-Ghazali" },
  { text: "Cinta kepada Allah adalah puncak segala kebaikan.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Orang yang kuat bukanlah yang pandai bergulat, tetapi yang mampu menahan amarahnya.", author: "HR. Bukhari" },
  { text: "Waktu adalah pedang. Jika kamu tidak memotongnya, ia yang akan memotongmu.", author: "Imam Syafi'i" },
  { text: "Jangan biarkan mataharimu terbenam dalam keadaan marah kepada siapapun.", author: "Pepatah Islam" },
  { text: "Sesungguhnya bersama kesulitan ada kemudahan.", author: "Al-Quran 94:6" },
  { text: "Mintalah pertolongan kepada Allah dengan sabar dan shalat.", author: "Al-Quran 2:153" },
  { text: "Muliakanlah tamu, karena ia membawa rezeki bersamanya.", author: "HR. Ibnu Majah" },
  { text: "Tanda keberhasilan seorang hamba adalah ia meninggalkan apa yang tidak bermanfaat baginya.", author: "HR. Tirmidzi" },
  { text: "Jangan berduka atas apa yang telah berlalu, dan jangan takut berlebihan atas yang belum datang.", author: "Ibnu Taimiyyah" },
  { text: "Hati yang bersih adalah hati yang bebas dari iri, dengki, dan rasa ingin menyakiti.", author: "Imam Al-Ghazali" },
  { text: "Hidup yang paling indah adalah hidup yang diisi dengan memberi.", author: "Ibnu Atha'illah" },
  { text: "Tawakkal bukan berarti berhenti berusaha, tapi menyerahkan hasilnya kepada Allah setelah berusaha.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Berbuat baiklah meski tidak ada yang melihat, karena Allah selalu melihat.", author: "Imam Al-Ghazali" },
  { text: "Orang yang bijak adalah yang selalu menghitung amalnya sebelum dihitung.", author: "Imam Ali bin Abi Thalib" },
  { text: "Jangan pernah menyepelekan doa, karena doa adalah senjata orang beriman.", author: "Imam Ali bin Abi Thalib" },
  { text: "Kebenaran itu berat tapi menyelamatkan, kebatilan itu ringan tapi menghancurkan.", author: "Ibnu Taimiyyah" },
  { text: "Sesungguhnya Allah tidak melihat rupa dan hartamu, tetapi Ia melihat hati dan amalmu.", author: "HR. Muslim" },
  { text: "Jadikan kesabaranmu sebagai pakaian, bukan penjara.", author: "Imam Syafi'i" },
  { text: "Siapa yang menyebarkan kebaikan, maka ia akan dibanjiri kebaikan.", author: "Imam Al-Ghazali" },
  { text: "Rezeki itu datang kepada yang bergerak, bukan yang hanya duduk menunggu.", author: "Pepatah Ulama" },
  { text: "Ketahuilah bahwa bersama kesabaran ada kemenangan.", author: "HR. Tirmidzi" },
  { text: "Jangan pernah malu belajar, karena belajar adalah tanda kerendahan hati.", author: "Imam Syafi'i" },
  { text: "Setiap langkah menuju kebaikan adalah ibadah.", author: "Imam An-Nawawi" },
  { text: "Ikhlaskan niatmu, maka amalmu akan ringan meski beratnya dunia.", author: "Ibnu Atha'illah" },
  { text: "Kesombongan adalah racun paling berbahaya bagi hati.", author: "Imam Al-Ghazali" },
  { text: "Orang yang paling beruntung adalah yang sedikit bicara banyak berbuat.", author: "Imam Ali bin Abi Thalib" },
  { text: "Hidup bukan soal berapa lama, tapi soal berapa banyak kamu memberi manfaat.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Jaga lisanmu, karena luka akibat lisan lebih dalam dari luka fisik.", author: "Imam Al-Ghazali" },
  { text: "Sesungguhnya Allah menyukai hamba yang tekun dan sungguh-sungguh dalam pekerjaannya.", author: "HR. Thabrani" },
  { text: "Bekerjalah untuk duniamu seolah kamu akan hidup selamanya, dan bekerjalah untuk akhiratmu seolah kamu akan mati besok.", author: "Imam Ali bin Abi Thalib" },
  { text: "Jangan biarkan kegagalan mengubahmu menjadi orang yang pesimis.", author: "Ibnu Taimiyyah" },
  { text: "Kunci kebahagiaan adalah rida terhadap takdir Allah.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Ilmu yang tidak diamalkan seperti awan yang tidak menurunkan hujan.", author: "Imam Syafi'i" },
  { text: "Perhatikan apa yang kamu katakan, karena kata-kata adalah cermin hatimu.", author: "Imam Ali bin Abi Thalib" },
  { text: "Jangan biarkan dunia menguasai hatimu, biarlah ia hanya di tanganmu.", author: "Ibnu Atha'illah" },
  { text: "Seorang mukmin tidak jatuh ke lubang yang sama dua kali.", author: "HR. Bukhari & Muslim" },
  { text: "Barangsiapa bertawakkal kepada Allah, maka Allah akan mencukupkan keperluannya.", author: "Al-Quran 65:3" },
  { text: "Cinta tanpa pengorbanan hanyalah kata-kata kosong.", author: "Imam Al-Ghazali" },
  { text: "Jangan merendahkan siapapun, karena setiap orang punya nilai di sisi Allah.", author: "Imam An-Nawawi" },
  { text: "Doa adalah inti ibadah.", author: "HR. Tirmidzi" },
  { text: "Sesungguhnya Allah tidak mengubah keadaan suatu kaum hingga mereka mengubah keadaan diri mereka sendiri.", author: "Al-Quran 13:11" },
  { text: "Keberanian sejati adalah berani berkata jujur meski pahit.", author: "Imam Ali bin Abi Thalib" },
  { text: "Bersyukurlah dalam keadaan sempit, niscaya Allah lapangkan jalanmu.", author: "Ibnu Atha'illah" },
  { text: "Kesederhanaan adalah mahkota orang beriman.", author: "Imam Ali bin Abi Thalib" },
  { text: "Harta yang paling berharga adalah akal yang sehat.", author: "Imam Al-Ghazali" },
  { text: "Jangan menunggu sempurna untuk memulai, mulailah maka kamu akan menjadi sempurna.", author: "Pepatah Ulama" },
  { text: "Setiap hari adalah kesempatan baru untuk menjadi lebih baik.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Jika engkau tidak bisa menjadi orang besar, jadilah orang yang bermanfaat.", author: "Imam Syafi'i" },
  { text: "Orang yang tidak pernah bersyukur tidak akan pernah merasa cukup.", author: "Imam Al-Ghazali" },
  { text: "Teguhkan hatimu, karena badai pasti berlalu.", author: "Imam Ali bin Abi Thalib" },
  { text: "Barang siapa yang menutup aib saudaranya, Allah akan menutup aibnya di dunia dan akhirat.", author: "HR. Muslim" },
  { text: "Jadikan shalat sebagai fondasi harimu, bukan sebagai pelengkap.", author: "Ibnu Taimiyyah" },
  { text: "Musuh terbesar manusia adalah hawa nafsunya sendiri.", author: "Imam Al-Ghazali" },
  { text: "Sesungguhnya waktu lebih berharga dari emas.", author: "Imam Syafi'i" },
  { text: "Jangan mengeluh tentang kegelapan, nyalakan saja lilinmu.", author: "Pepatah Islam" },
  { text: "Siapa yang bersungguh-sungguh, ia akan berhasil.", author: "Pepatah Arab (Man Jadda Wajada)" },
  { text: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.", author: "Al-Quran 2:286" },
  { text: "Senyum kepada saudaramu adalah sedekah.", author: "HR. Tirmidzi" },
  { text: "Ilmu adalah cahaya, dan cahaya Allah tidak diberikan kepada orang yang bermaksiat.", author: "Imam Syafi'i" },
  { text: "Jangan berdebat dengan orang bodoh, karena penonton tidak akan tahu siapa yang bodoh.", author: "Imam Al-Ghazali" },
  { text: "Sesungguhnya dunia ini hanya tempat singgah sementara.", author: "HR. Bukhari" },
  { text: "Bertemanlah dengan orang saleh meski kamu tidak setara, karena kebaikan itu menular.", author: "Imam Al-Ghazali" },
  { text: "Yang paling dekat dengan Allah adalah yang paling banyak mengingatNya.", author: "Imam An-Nawawi" },
  { text: "Jangan takut berbeda, takutlah tidak memberikan kontribusi.", author: "Ibnu Taimiyyah" },
  { text: "Hargai orang lain jika ingin dihargai.", author: "Imam Ali bin Abi Thalib" },
  { text: "Sesungguhnya setelah kesulitan pasti ada kemudahan.", author: "Al-Quran 94:5" },
  { text: "Orang yang meninggalkan sesuatu karena Allah, Allah akan menggantinya dengan yang lebih baik.", author: "HR. Ahmad" },
  { text: "Rendahkanlah dirimu di hadapan Allah agar Allah meninggikanmu.", author: "Imam Al-Ghazali" },
  { text: "Jangan biarkan amarahmu merusak hari yang baik.", author: "Imam Ali bin Abi Thalib" },
  { text: "Kejujuran adalah modal utama kepercayaan.", author: "Imam Syafi'i" },
  { text: "Sebaik-baik amal adalah yang paling konsisten meski sedikit.", author: "HR. Bukhari & Muslim" },
  { text: "Dunia adalah ladang akhirat, maka tanamlah kebaikan di dalamnya.", author: "Imam Al-Ghazali" },
  { text: "Tidaklah beriman seseorang hingga ia mencintai untuk saudaranya apa yang ia cintai untuk dirinya.", author: "HR. Bukhari" },
  { text: "Keberkahan ada dalam kesederhanaan.", author: "Ibnu Atha'illah" },
  { text: "Sesungguhnya Allah menyukai hambaNya yang pandai bersyukur.", author: "Imam Al-Ghazali" },
  { text: "Jangan sia-siakan waktu mudamu, karena waktu tidak akan kembali.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Orang yang berilmu dan orang yang bodoh tidak akan pernah sama.", author: "Al-Quran 39:9" },
  { text: "Bertanyalah kepada ahlinya jika kamu tidak tahu, itu adalah kerendahan hati.", author: "Imam Syafi'i" },
  { text: "Keikhlasan adalah ruh dari setiap amal.", author: "Imam Al-Ghazali" },
  { text: "Jadilah bagian dari solusi, bukan bagian dari masalah.", author: "Ibnu Taimiyyah" },
  { text: "Hidup adalah perjalanan, maka pastikan tujuanmu adalah ridha Allah.", author: "Ibnu Qayyim Al-Jauziyyah" },
  { text: "Sesungguhnya Allah itu indah dan menyukai keindahan.", author: "HR. Muslim" },
]

export function getDailyQuote() {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now - start
  const oneDay = 1000 * 60 * 60 * 24
  const dayOfYear = Math.floor(diff / oneDay)
  const index = dayOfYear % 100
  return quotes[index]
}
